### ISSUE TITLE
Error on automated re-add

### ISSUE THREAD

**Issue by Landelor** [haijeploeg/excludarr#40]
**Describe the bug**
Whenever running radarr re-add with -y switch there is an error when something is available to add.

**To Reproduce**
1. excludarr radarr re-add -y

**Expected behavior**
Re-add any found movies without error.

**Versions**
1. OS Version: .unRAID
2. Excludarr version: 1.0.3
3. Python version:  Python - 2.7.11 | Python3 - 3.9.0

**Debug logging**
Traceback (most recent call last):
  File "/usr/bin/excludarr", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib64/python3.9/site-packages/excludarr/main.py", line 68, in cli
    app(prog_name="excludarr")
  File "/usr/lib64/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/lib64/python3.9/site-packages/excludarr/commands/radarr.py", line 207, in re_add
    if confirmation:
UnboundLocalError: local variable 'confirmation' referenced before assignment

**Additional context**

**Comment by haijeploeg** [comment]
Hi Landelor!

Thanks for your issue. It was indeed a bug, thanks for pointing that one out. I also verified if the other commands did have the same problem. Fortunately they were okay. Going to fix this right now, you can download version 1.0.4 in about 30 minutes :)
