### ISSUE TITLE
Max retries exceeded with url: /api/v3/series

### ISSUE THREAD

**Issue by jkulker** [haijeploeg/excludarr#55]
**Describe the bug**
Try to run the application in docker: gives me the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/excludarr", line 33, in <module>
    sys.exit(load_entry_point('excludarr==1.0.6', 'console_scripts', 'excludarr')())
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/main.py", line 68, in cli
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/commands/sonarr.py", line 69, in exclude
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/core/sonarr_actions.py", line 160, in get_series_to_exclude
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/modules/pysonarr/v3/serie.py", line 13, in get_all_series
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/modules/pysonarr/__init__.py", line 74, in http_get
  File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.6-py3.10.egg/excludarr/modules/pysonarr/__init__.py", line 62, in http_request
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8989): Max retries exceeded with url: /api/v3/series (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa68a6bdae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**To Reproduce**
1. docker run -it --rm --env-file excludarr.env haijeploeg/excludarr:latest sonarr exclude -a not-monitored

**Expected behavior**
Succesful running in Docker

**Versions**
Windows 10

**Comment by jkulker** [comment]
Hi there you are correct i changed the localhost to a ip address and it fixed the issue
