### ISSUE TITLE
Error when Running for Radarr

### ISSUE THREAD

**Issue by ohsnapword** [haijeploeg/excludarr#85]
**Describe the bug**
Excludarr fails to process commands for Radarr.

**To Reproduce**
Cron job "excludarr radarr exclude -a not-monitored -d -e -y"
Confg file:
general:
  fast_search: true
  locale: en_US
  providers: [Hulu,Disney Plus,Paramount Plus]

radarr:
  url: 'http://192.168.1.3:7878/'
  api_key: 'radarrapi'
  verify_ssl: false
  exclude: ['']

sonarr:
  url: '192.168.1.4:8989/'
  api_key: 'sonarrapi'
  verify_ssl: false
  exclude: ['']

tmdb:
  api_key: 'tmdbapi'

**Expected behavior**
Command runs successfully

**Versions**
Docker container

**Debug logging**
0Traceback (most recent call last):
2023-04-24 07:00:04.149011+00:00File "/usr/local/bin/excludarr", line 33, in <module>
2023-04-24 07:00:04.149879+00:00sys.exit(load_entry_point('excludarr==1.0.7', 'console_scripts', 'excludarr')())
2023-04-24 07:00:04.149906+00:00File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.7-py3.10.egg/excludarr/main.py", line 68, in cli
2023-04-24 07:00:04.150039+00:00File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
2023-04-24 07:00:04.164467+00:00return get_command(self)(*args, **kwargs)
2023-04-24 07:00:04.164509+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2023-04-24 07:00:04.182453+00:00return self.main(*args, **kwargs)
2023-04-24 07:00:04.182494+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
2023-04-24 07:00:04.182899+00:00rv = self.invoke(ctx)
2023-04-24 07:00:04.182924+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
2023-04-24 07:00:04.183545+00:00return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-04-24 07:00:04.183570+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
2023-04-24 07:00:04.184148+00:00return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-04-24 07:00:04.184176+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2023-04-24 07:00:04.184719+00:00return ctx.invoke(self.callback, **ctx.params)
2023-04-24 07:00:04.184744+00:00File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2023-04-24 07:00:04.185057+00:00return __callback(*args, **kwargs)
2023-04-24 07:00:04.185072+00:00File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
2023-04-24 07:00:04.185375+00:00return callback(**use_params)  # type: ignore
2023-04-24 07:00:04.185400+00:00File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.7-py3.10.egg/excludarr/commands/radarr.py", line 84, in exclude
2023-04-24 07:00:04.185428+00:00File "/usr/local/lib/python3.10/site-packages/excludarr-1.0.7-py3.10.egg/excludarr/core/radarr_actions.py", line 98, in get_movies_to_exclude
2023-04-24 07:00:04.185455+00:00TypeError: byte indices must be integers or slices, not str
2023-04-24 10:01:13.449481+00:002023-04-24T10:01:13.449481756Z
If the output is too long, please paste the output to pastebin or github gist and link it in this issue.

**Additional context**

**Comment by ohsnapword** [comment]
I fixed it.  Turns out that it didn't like the trailing "/" in the Radarr URL.
